#Created by webjeda - http://webjeda.com

title: Chalas Zico
email: contacto@chalaszico.cl


baseurl: /chalaszico

sass:
 style: compressed


# Tracker
analytics: 

### exclude the instructions / write-up in the README.md
exclude:
- README.md
